server {
  listen 8080;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass http://app:3000/api/;
  }

  location = /swagger.yaml {
    sub_filter 'host: "releases-api.app"' 'host: "localhost:8081"';
    sub_filter_once on;
    sub_filter_types *;
  }

  location / {}
}
